Return error if tool check fails
Note we leave 68000 out because we'd otherwise break the CI which
lazily uses (the broken) m68k-linux-gcc for compile check.

Signed-off-by: Tormod Volden <debian.tormod@gmail.com>

diff --git a/Tools/build-armm0 b/Tools/build-armm0
--- a/Tools/build-armm0
+++ b/Tools/build-armm0
@@ -2,5 +2,6 @@
 
 X=`which /opt/gcc-arm-eabi/bin/arm-none-eabi-gcc`
 if [ "$X" = "" ]; then
-	echo "gcc: /opt/gcc-arm-eabi/bin/arm-none-eabi-gcc"
+	echo "gcc: /opt/gcc-arm-eabi/bin/arm-none-eabi-gcc is required"
+	exit 1
 fi
diff --git a/Tools/build-riscv32 b/Tools/build-riscv32
--- a/Tools/build-riscv32
+++ b/Tools/build-riscv32
@@ -2,5 +2,6 @@
 
 X=`which riscv-unknown-elf-gcc`
 if [ "$X" = "" ]; then
-	echo "gcc: riscv-unknown-elf-gcc"
+	echo "gcc: riscv-unknown-elf-gcc is required"
+	exit 1
 fi
